// course/chapter4/react_app/src/Hello.js
import React from 'react';

const Hello = ({ backgroundColor }) => {
  const style = {
    backgroundColor,
    width: 200,
    height: 50,
    lineHeight: '50px',
    fontSize: 50,
    borderRadius: 10,
    color: 'black',
  };
  return (
    <div style={style}>Hello</div>
  );
};

export default Hello;

// course/chapter4/vue-app/src/components/Hello.vue
<template>
  <div class="helloCSS" v-bind:style="style">
    Hello
  </div>
</template>

<script>
export default {
  name: 'Hello',
  props: {
    backgroundColor: String
  },
  computed: {
    style () {
      return 'background-color: ' + this.backgroundColor;
    }
  },
}
</script>

<style scoped>
.helloCSS{
  width: 200px;
  height: 50px; 
  line-height: 50px;
  font-size: 50px;
  border-radius: 10px;
  color: black;
}
</style>
